let _ = require('lodash');

let tower = {
    'vpryah': { weight: 0, children: ['iedlpkf', 'epeain'] },
    'aqfemi': { weight: 8 },
    'bwtsue': { weight: 8, children: ['crdoq', 'lhxdfj'] },
    'eeyaxfn': { weight: 2, children: ['idsab', 'jnhyc', 'vswgxoh', 'hivnzrk', 'afcsq', 'vpryah', 'dqiby'] },
    'vddsv': { weight: 4 },
    'xnoux': { weight: 1 },
    'apajk': { weight: 1 },
    'fdgjgwt': { weight: 4, children: ['piofa', 'uxrros', 'ngiys'] },
    'tgjmrpl': { weight: 3 },
    'jjxhgkx': { weight: 8, children: ['jncwn', 'tydjgm'] },
    'nbrqwvs': { weight: 1, children: ['zzkzfln', 'htdimcs'] },
    'qcnoadr': { weight: 0 },
    'wwcngr': { weight: 7 },
    'deweh': { weight: 9, children: ['qaqof', 'kvyiqr', 'zfmqlj'] },
    'ygeoklq': { weight: 2 },
    'bpszadt': { weight: 5 },
    'bdlzzvy': { weight: 8 },
    'fbaiatg': { weight: 3 },
    'pidgnp': { weight: 6, children: ['ehlwoxs', 'hbldvzk', 'ezwzp', 'tylelk', 'jkxutle', 'kkflx', 'oucqw'] },
    'vijgqvl': { weight: 0 },
    'ofjjqdj': { weight: 6 },
    'vgsqrp': { weight: 6 },
    'idqgxkl': { weight: 1 },
    'nafzy': { weight: 5 },
    'nxspzd': { weight: 2 },
    'cnrwew': { weight: 2, children: ['vnyaqgw', 'zooxx'] },
    'qhdqak': { weight: 1, children: ['vmgxg', 'knmmys', 'zkwplas', 'bsqpcne', 'xgqdjhe'] },
    'rxbrsd': { weight: 8 },
    'hubvoh': { weight: 2 },
    'mpwlly': { weight: 2 },
    'rotzn': { weight: 0 },
    'drswab': { weight: 7 },
    'udkvb': { weight: 0, children: ['fkvhdj', 'flhhbd'] },
    'coedb': { weight: 2 },
    'fpwoels': { weight: 5 },
    'huzzk': { weight: 1, children: ['fqozst', 'naacbhr'] },
    'etxfihy': { weight: 8, children: ['tgjmrpl', 'hdiprgd', 'hospabk', 'fvmws'] },
    'mbtin': { weight: 7 },
    'yaawixo': { weight: 7 },
    'kxcid': { weight: 7 },
    'sibko': { weight: 7 },
    'khshj': { weight: 7 },
    'otnrfom': { weight: 7 },
    'hzqpddb': { weight: 6 },
    'ngiys': { weight: 3, children: ['ybqzq', 'vcrgmn', 'ysmqsps', 'bwrenq', 'opomx'] },
    'yybtd': { weight: 6 },
    'myhgys': { weight: 1, children: ['daesbhs', 'qrmipn'] },
    'amhmm': { weight: 4, children: ['pxkhwuu', 'gnbmz'] },
    'soiza': { weight: 4 },
    'dqiby': { weight: 2, children: ['fdklcbu', 'qcnoadr'] },
    'jleqdi': { weight: 9 },
    'fdyuo': { weight: 1 },
    'gxmdnq': { weight: 2 },
    'wdnlqh': { weight: 3 },
    'lmmffej': { weight: 7, children: ['twjvtbu', 'suvwi'] },
    'qrrdb': { weight: 4, children: ['zqvhd', 'vcgcmuh'] },
    'gkzpb': { weight: 7 },
    'rfkdn': { weight: 3, children: ['zpjju', 'bxwtlj', 'igzrzi'] },
    'iyegmn': { weight: 8 },
    'johqe': { weight: 7 },
    'nmfhgq': { weight: 1, children: ['dzbnx', 'cveuc', 'sfrwf'] },
    'jknrln': { weight: 3 },
    'hivnzrk': { weight: 6, children: ['coxuqy', 'ewuohku'] },
    'xulpd': { weight: 4, children: ['itzmwqp', 'egtem'] },
    'quqixmj': { weight: 3, children: ['jykfxee', 'vsqcws'] },
    'wjkfdvb': { weight: 0 },
    'fusiiz': { weight: 7 },
    'awvqy': { weight: 1 },
    'auztp': { weight: 7 },
    'ghuyt': { weight: 5 },
    'xzfrad': { weight: 3 },
    'nvkhow': { weight: 6 },
    'htdimcs': { weight: 3 },
    'kwolrk': { weight: 0 },
    'dhsyxu': { weight: 5 },
    'chjdhl': { weight: 0 },
    'gndjq': { weight: 0 },
    'izxeuz': { weight: 7 },
    'dgqquh': { weight: 2 },
    'yenbb': { weight: 1 },
    'wogrc': { weight: 7 },
    'cijhcl': { weight: 6 },
    'ebaevkk': { weight: 7 },
    'mxikfk': { weight: 3 },
    'elxfl': { weight: 0, children: ['ohneffn', 'jyvhtle', 'sgymtmx', 'mitvkt', 'kaxvdwl'] },
    'aivprd': { weight: 8 },
    'ujnas': { weight: 4 },
    'ubdfq': { weight: 2 },
    'ozuqsau': { weight: 8 },
    'hlszj': { weight: 3 },
    'tpdch': { weight: 7 },
    'atgamme': { weight: 6 },
    'nwlacty': { weight: 7, children: ['vhuwgi', 'zaiopar'] },
    'kyizmdu': { weight: 3 },
    'xgufltj': { weight: 6 },
    'rqbjjuo': { weight: 9 },
    'pkipyhb': { weight: 8 },
    'mojsngw': { weight: 2 },
    'bncmd': { weight: 5 },
    'hkssn': { weight: 3, children: ['gjpglfg', 'bqlmhj', 'cvseh'] },
    'mgoew': { weight: 0, children: ['gqmbul', 'geqrb', 'oidjn'] },
    'fdvfx': { weight: 8 },
    'mkohhbb': { weight: 2 },
    'btami': { weight: 1 },
    'ohbhyq': { weight: 0 },
    'jnyvdz': { weight: 8 },
    'sbzee': { weight: 4 },
    'dyeds': { weight: 7 },
    'xmendwz': { weight: 6 },
    'dwybhqe': { weight: 6, children: ['ftyilib', 'lhmhrpi'] },
    'dydlyj': { weight: 8 },
    'cgtddkw': { weight: 4, children: ['jcikl', 'jaxjy'] },
    'jircuj': { weight: 9, children: ['qyqthsz', 'ctqaxh', 'scbjq'] },
    'xernf': { weight: 4 },
    'ljpeina': { weight: 1 },
    'dvvlx': { weight: 6 },
    'itzmwqp': { weight: 6 },
    'opbrn': { weight: 8 },
    'ekpvnh': { weight: 1 },
    'btbuwwi': { weight: 5, children: ['btami', 'ffrrwb', 'niuvu', 'atzuayu'] },
    'ceqayn': { weight: 7 },
    'gtgdmny': { weight: 1 },
    'unqmapv': { weight: 8, children: ['ofjjqdj', 'vgsqrp', 'ayogkum', 'ymerus'] },
    'phrrm': { weight: 5 },
    'botmw': { weight: 8 },
    'fbhxulf': { weight: 0, children: ['flbumzk', 'csxdpl'] },
    'tdbwpcj': { weight: 8 },
    'qdfzlv': { weight: 3, children: ['blkcnq', 'idqgxkl'] },
    'cfiurqp': { weight: 2 },
    'pejkmud': { weight: 3 },
    'doqxpij': { weight: 4, children: ['xaidhn', 'mcmijwy'] },
    'mmjpziu': { weight: 8 },
    'ryjrq': { weight: 9 },
    'dzienj': { weight: 5, children: ['gybbvb', 'mbtin'] },
    'iisuf': { weight: 2 },
    'mtfqemm': { weight: 8 },
    'gwpzvb': { weight: 8, children: ['qjlrpjn', 'prtah'] },
    'pkjykh': { weight: 1 },
    'hgqesr': { weight: 2, children: ['satuz', 'zozajw', 'hzauzw'] },
    'ayogkum': { weight: 6 },
    'cdqkuuw': { weight: 6, children: ['lhjpci', 'mlkddpw'] },
    'dvips': { weight: 3 },
    'klvhv': { weight: 4 },
    'kvypj': { weight: 1 },
    'rcytc': { weight: 0, children: ['doqxpij', 'dwybhqe', 'yeuaeqp', 'bpvit', 'ljhqql'] },
    'wadeqe': { weight: 8 },
    'dqwocyn': { weight: 5, children: ['aepss', 'jtxphqg', 'gveca'] },
    'unbjm': { weight: 0 },
    'qhwtf': { weight: 7 },
    'afxazvx': { weight: 9 },
    'pyraep': { weight: 6 },
    'lwpwtbj': { weight: 1 },
    'kasozsw': { weight: 3, children: ['sayhdkv', 'ghhhiwl', 'kreehw'] },
    'xfjpbus': { weight: 6 },
    'llalv': { weight: 5 },
    'xpzadg': { weight: 5, children: ['ydjrtcd', 'ebaevkk'] },
    'igzrzi': { weight: 2, children: ['chjdhl', 'buyou'] },
    'skzxsyk': { weight: 1 },
    'hontwg': { weight: 8, children: ['pgnbhl', 'qoksme', 'dzlgor', 'gmfsl', 'sdvag', 'nbrqwvs'] },
    'smmdlo': { weight: 6, children: ['cxgdzl', 'facddx', 'doehwd'] },
    'drtfi': { weight: 9 },
    'uglla': { weight: 9 },
    'mjbdmlf': { weight: 7 },
    'ykhycl': { weight: 6, children: ['xmkkpat', 'iroikgp', 'khshj', 'kxqhlbm', 'vfrna'] },
    'twvkgl': { weight: 4 },
    'iuagzo': { weight: 9 },
    'qxvpdh': { weight: 8, children: ['qptzj', 'hkcghm'] },
    'poviv': { weight: 6 },
    'knhati': { weight: 1 },
    'uashrrc': { weight: 0 },
    'ouiwlb': { weight: 8 },
    'tzxvnri': { weight: 2 },
    'bnqutso': { weight: 1 },
    'fqozst': { weight: 9 },
    'xypex': { weight: 8 },
    'gerpefi': { weight: 9 },
    'wbqjf': { weight: 4 },
    'xaidhn': { weight: 1 },
    'lwpmgk': { weight: 1 },
    'wuluf': { weight: 2 },
    'ffrrwb': { weight: 1 },
    'ooobx': { weight: 5 },
    'fdhvp': { weight: 7, children: ['ybjld', 'uksim', 'wbqjf', 'sbzee'] },
    'pxkhwuu': { weight: 9 },
    'rrxrsx': { weight: 7 },
    'crxbcqe': { weight: 3, children: ['rmocf', 'xjiql', 'mocrsqu'] },
    'msywua': { weight: 2 },
    'zqatt': { weight: 2, children: ['pzggi', 'abdjb', 'wvisr', 'ibushn', 'fdkvm', 'dobqmg', 'gbqig'] },
    'jfclt': { weight: 7, children: ['pjssvle', 'tmsnmf', 'iisuf', 'njhppm'] },
    'upndyov': { weight: 3, children: ['pkcpn', 'qvknu'] },
    'gbbnux': { weight: 9, children: ['yotrh', 'bnsqqv'] },
    'scbjq': { weight: 9, children: ['ogorkv', 'rvglq', 'upnls'] },
    'ydgusm': { weight: 6 },
    'sayhdkv': { weight: 7 },
    'nqzlzs': { weight: 0 },
    'coazy': { weight: 9, children: ['wkmey', 'skzxsyk'] },
    'vhcza': { weight: 0 },
    'pgtmio': { weight: 9 },
    'tprgqt': { weight: 1 },
    'euoqdcd': { weight: 2 },
    'zddlo': { weight: 2 },
    'dlapc': { weight: 6 },
    'qorsgjk': { weight: 2 },
    'hsyoiy': { weight: 3 },
    'pyplv': { weight: 6 },
    'gqmbul': { weight: 8 },
    'jwgvg': { weight: 2 },
    'lyrxhp': { weight: 0 },
    'uekiz': { weight: 3, children: ['wwcngr', 'xqyrozn', 'ikclk', 'uents'] },
    'ibyvotn': { weight: 5 },
    'ewtqg': { weight: 1 },
    'qwlze': { weight: 2, children: ['malwro', 'gwyrxmf', 'blstaec', 'ehoqrji', 'bqppw', 'btbuwwi'] },
    'gjpglfg': { weight: 9, children: ['vumpiw', 'yfzbdl', 'nlgoig', 'fqppio', 'uykfql', 'gvujhex'] },
    'ftohrkw': { weight: 6 },
    'hmtnj': { weight: 8, children: ['qorsgjk', 'vneld'] },
    'qggjzz': { weight: 6, children: ['yqxvhbl', 'wsyqwf'] },
    'pgilb': { weight: 9 },
    'hueuhx': { weight: 4 },
    'thats': { weight: 4 },
    'arveor': { weight: 0 },
    'yuymxvd': { weight: 0, children: ['llbxkj', 'zmpyqv'] },
    'cisaxsf': { weight: 1, children: ['rptfwu', 'mqjpes'] },
    'pkuqykh': { weight: 8, children: ['bpyce', 'fusiiz', 'mdrto'] },
    'otqdauw': { weight: 2 },
    'ylnua': { weight: 6 },
    'uyjtxt': { weight: 7, children: ['gahwap', 'fqxrjg', 'mnxmtp'] },
    'zfzpgfw': { weight: 5, children: ['rwouyb', 'gjvfc', 'zbtswr'] },
    'vzrfuvn': { weight: 3 },
    'bdzkzv': { weight: 8, children: ['baimp', 'wfgyg'] },
    'ceywcm': { weight: 8 },
    'ypeap': { weight: 0 },
    'mqjqez': { weight: 0 },
    'iueqa': { weight: 3 },
    'hqhkw': { weight: 0 },
    'bpyce': { weight: 7 },
    'wseii': { weight: 6 },
    'vxxhu': { weight: 2 },
    'nqomdre': { weight: 0 },
    'pxnvwaj': { weight: 1, children: ['rcytc', 'hontwg', 'vjhwn', 'deweh'] },
    'qvknu': { weight: 0 },
    'qcsfpn': { weight: 5 },
    'eprljo': { weight: 8, children: ['hdjlp', 'qqfgo', 'xbhww'] },
    'cwdfqo': { weight: 6, children: ['ctqym', 'nxxfgn', 'uoenrx', 'owdcg'] },
    'fgzwvuy': { weight: 7 },
    'ajdtudl': { weight: 3 },
    'dngqchs': { weight: 2, children: ['mxpxbm', 'quqixmj', 'qneezf'] },
    'zdiygz': { weight: 7, children: ['tujrz', 'vpmuei'] },
    'jkxutle': { weight: 7, children: ['scjrx', 'srcfgoo', 'rfkdn'] },
    'jeywnj': { weight: 3, children: ['kkjro', 'jxysad', 'crxbcqe', 'pgdgh', 'qozxrgg'] },
    'holcno': { weight: 3 },
    'qtjpthc': { weight: 5, children: ['hfpspc', 'iniuzfq'] },
    'malwro': { weight: 3, children: ['saxar', 'dydlyj'] },
    'bujphvu': { weight: 4, children: ['dpcuy', 'rimobjs', 'mevce'] },
    'hgogzfl': { weight: 7 },
    'xgqdjhe': { weight: 7, children: ['gbbnux', 'zuanzd', 'nbykdlk'] },
    'rtzodmx': { weight: 6 },
    'mdrto': { weight: 7 },
    'xuwmc': { weight: 6, children: ['yekxli', 'xnfybs'] },
    'ptmqsnr': { weight: 3 },
    'mplgqv': { weight: 7 },
    'uhoryyb': { weight: 7, children: ['slohro', 'kkjnouk', 'lmfchi'] },
    'yrbwhz': { weight: 9 },
    'elcnwtn': { weight: 0, children: ['mmqtzmj', 'rnfoji', 'xayhv'] },
    'wtkxd': { weight: 3 },
    'ftyilib': { weight: 5 },
    'bztcy': { weight: 4, children: ['mysjwy', 'wbqkf'] },
    'unnvung': { weight: 4 },
    'gufqi': { weight: 2 },
    'zntrkc': { weight: 1 },
    'zxdhxrb': { weight: 9 },
    'tzvtu': { weight: 8 },
    'ohneffn': { weight: 5, children: ['ffcefem', 'qjxyfa', 'bojjcl', 'bhqkvi'] },
    'rtcicn': { weight: 1, children: ['hqcwl', 'pgilb', 'dniub'] },
    'hmwfqwz': { weight: 5, children: ['zqczqd', 'xdrjmkv'] },
    'obilnz': { weight: 3 },
    'satuz': { weight: 1 },
    'fdkvm': { weight: 9, children: ['hueuhx', 'ujyxvl'] },
    'mxtcei': { weight: 4, children: ['eeyaxfn', 'dhrbaor', 'mzgayzs', 'tfphsaq'] },
    'cqupm': { weight: 1, children: ['vsvne', 'wwrkqb', 'jtgcmc', 'yyria', 'hkntpfd', 'cbefqk'] },
    'gymuodz': { weight: 3, children: ['rimua', 'whfeq'] },
    'zfmqlj': { weight: 1, children: ['kdbfv', 'abccyo'] },
    'muecxv': { weight: 8 },
    'cldldxp': { weight: 4, children: ['uuztubk', 'hrqsnls', 'eeergq', 'vyqlzi'] },
    'acpwe': { weight: 5, children: ['yrbpdq', 'iwtqde'] },
    'hcrxqbw': { weight: 0 },
    'xmkkpat': { weight: 3, children: ['ivwybv', 'mjbdmlf'] },
    'okqwb': { weight: 5 },
    'pwmazwj': { weight: 9 },
    'qwtheza': { weight: 2 },
    'euxrv': { weight: 0, children: ['sfuegcs', 'kqfesp', 'azjunml'] },
    'qvowcc': { weight: 0 },
    'zelwp': { weight: 1, children: ['nxspzd', 'lrhkoc', 'ybfqzep', 'sqwovza'] },
    'pqqfpa': { weight: 5, children: ['dezgi', 'dtakrnu'] },
    'uykfql': { weight: 5, children: ['efijtd', 'phdetz'] },
    'jyvhtle': { weight: 5, children: ['jasol', 'esivz', 'wprhap', 'fqyog'] },
    'czyok': { weight: 5, children: ['pkipyhb', 'sbsfo', 'izkej'] },
    'vpmuei': { weight: 2 },
    'ydjrtcd': { weight: 7 },
    'bgjwy': { weight: 2 },
    'xupkjdt': { weight: 1, children: ['mzjhsq', 'cimubay'] },
    'coxuqy': { weight: 8 },
    'wupsg': { weight: 1 },
    'prtah': { weight: 9 },
    'pewvv': { weight: 9, children: ['rtcicn', 'vysjpf', 'lxxbgm', 'bztcy', 'fgbsxh'] },
    'kemme': { weight: 8 },
    'rpanfr': { weight: 2 },
    'mmqtzmj': { weight: 6 },
    'auocefh': { weight: 0 },
    'mweox': { weight: 0, children: ['ddrsd', 'nxwtdg', 'jlvakq', 'gmaxala', 'rtwur', 'qqkwjoy', 'lmmffej'] },
    'kazlt': { weight: 2, children: ['cgetpc', 'jknrln'] },
    'rqqxoou': { weight: 2, children: ['lbeqp', 'jfsnic'] },
    'jrygk': { weight: 4, children: ['zkkvh', 'xjvwjq'] },
    'rvglq': { weight: 8 },
    'ajyzem': { weight: 0 },
    'qhgvoj': { weight: 9, children: ['uwpuqd', 'pyplv'] },
    'scgpm': { weight: 9 },
    'apbjfv': { weight: 3 },
    'waxvx': { weight: 6 },
    'dpqrxbr': { weight: 5, children: ['nafzy', 'bgscxgk'] },
    'jtzrvt': { weight: 5 },
    'qnzdaj': { weight: 2, children: ['ablgyqv', 'xhang'] },
    'jfvoui': { weight: 5 },
    'vfmiaz': { weight: 8 },
    'xnqznos': { weight: 5 },
    'qhfoy': { weight: 3 },
    'fsqws': { weight: 5, children: ['yyrwb', 'vnuwoq', 'vlllp', 'reuaanp'] },
    'aunrdo': { weight: 1 },
    'pbcpt': { weight: 7 },
    'xwunxz': { weight: 0, children: ['klhzgvj', 'walzh', 'snquxtz'] },
    'lshkygc': { weight: 9 },
    'bkqndr': { weight: 4 },
    'dhrbaor': { weight: 1, children: ['fpkuumw', 'fytlv', 'knendm', 'xxsobt', 'wlqfnkr'] },
    'opomx': { weight: 1, children: ['pycim', 'khnemp'] },
    'zlvgiq': { weight: 6 },
    'oioqg': { weight: 3 },
    'dkeosz': { weight: 3 },
    'irgymg': { weight: 9 },
    'iyqcty': { weight: 9 },
    'ozugcs': { weight: 0 },
    'ewoebye': { weight: 5 },
    'dxggcx': { weight: 4, children: ['nuwpvd', 'ylnua', 'vljooo', 'ykzjkp'] },
    'qyvxs': { weight: 3, children: ['qtcsae', 'gjdrco', 'zffoytm'] },
    'ogorkv': { weight: 8 },
    'zuanzd': { weight: 3, children: ['tutmv', 'ubkhce', 'ebzton'] },
    'qozxrgg': { weight: 1, children: ['yuymxvd', 'zjuupn', 'uyjtxt'] },
    'lbeqp': { weight: 2 },
    'bqlmhj': { weight: 6, children: ['cvahi', 'jgbvdp', 'wehfli'] },
    'ptyuh': { weight: 0 },
    'jlhsd': { weight: 1, children: ['ygnlbv', 'wochkc', 'nzazpe'] },
    'ayfafvc': { weight: 3 },
    'ldmgzql': { weight: 7, children: ['qsods', 'ewoebye', 'yesozb', 'bfqotji'] },
    'rdytzgp': { weight: 4, children: ['uhoryyb', 'vfwwc', 'hkssn'] },
    'nxxfgn': { weight: 9 },
    'iniuzfq': { weight: 1 },
    'vysjpf': { weight: 8, children: ['ohbhyq', 'bhzeep'] },
    'scjrx': { weight: 8, children: ['ejoee', 'uyvuqp', 'yaera'] },
    'tzobgt': { weight: 8 },
    'ljhqql': { weight: 4, children: ['tbzqsrb', 'wtkxd', 'amhug', 'axgpt'] },
    'vvpacb': { weight: 6, children: ['ijmaxm', 'cjoeyrm'] },
    'zqvhd': { weight: 8 },
    'zagaz': { weight: 8 },
    'emhblpr': { weight: 5 },
    'lrosl': { weight: 2 },
    'orcrc': { weight: 4 },
    'vyfhcqp': { weight: 9, children: ['jwgvg', 'pyfeav'] },
    'njhppm': { weight: 2 },
    'eowjgp': { weight: 8, children: ['ueqkrm', 'nhgchm'] },
    'wlodh': { weight: 9 },
    'vsqcws': { weight: 5 },
    'jxcxv': { weight: 0 },
    'hybvw': { weight: 2 },
    'qdgsn': { weight: 7 },
    'jasol': { weight: 1 },
    'zgrcahy': { weight: 4 },
    'mhassg': { weight: 0 },
    'eeergq': { weight: 3, children: ['oeehfxg', 'emhblpr'] },
    'ojozup': { weight: 9 },
    'gmeqmy': { weight: 6, children: ['mbslas', 'vimplcz'] },
    'zzekx': { weight: 1 },
    'xjvwjq': { weight: 4 },
    'heezga': { weight: 0, children: ['jtfdy', 'scgpm'] },
    'pjhoue': { weight: 6 },
    'djejdy': { weight: 8, children: ['fdvfx', 'ykoazai'] },
    'fkzxmb': { weight: 5 },
    'ezwzp': { weight: 9, children: ['jlhsd', 'oedan', 'emuek'] },
    'tlwqwlk': { weight: 3 },
    'fqyog': { weight: 1 },
    'elvzp': { weight: 3 },
    'ydusqh': { weight: 0, children: ['qucxsqh', 'lrfttlb', 'vzrfuvn', 'ptmqsnr'] },
    'dweli': { weight: 8 },
    'qbnldp': { weight: 5, children: ['cguzndh', 'oldoxo'] },
    'xbhww': { weight: 5 },
    'smjtypd': { weight: 5 },
    'vcgcmuh': { weight: 8 },
    'iedlpkf': { weight: 6 },
    'zttytvi': { weight: 3, children: ['qkjed', 'jnxbxzk'] },
    'bszaj': { weight: 4, children: ['txhbij', 'kwolrk'] },
    'qwagq': { weight: 7 },
    'gxzxapn': { weight: 2 },
    'fqppio': { weight: 9, children: ['fllao', 'orcrc', 'uhmmouc', 'twvkgl'] },
    'opnpx': { weight: 4 },
    'esivz': { weight: 1 },
    'iqbtc': { weight: 4 },
    'wznad': { weight: 9 },
    'nujmyt': { weight: 9, children: ['vbzyp', 'qwagq'] },
    'vuzkop': { weight: 7 },
    'dxzahps': { weight: 8 },
    'idsab': { weight: 2, children: ['befsr', 'mhlgi', 'uashrrc', 'fkmyndg'] },
    'vtjrflg': { weight: 3 },
    'wfgyg': { weight: 9 },
    'ghhhiwl': { weight: 7 },
    'phpjy': { weight: 4 },
    'ekffumh': { weight: 5, children: ['wznad', 'metsfo', 'afycii', 'czyok'] },
    'jhltpk': { weight: 1 },
    'kaxvdwl': { weight: 5, children: ['hzqpddb', 'aqeqvr', 'esegn', 'hdyrxg'] },
    'uxgux': { weight: 3 },
    'zhnug': { weight: 7 },
    'cjoeyrm': { weight: 2 },
    'sdvag': { weight: 7 },
    'efbvz': { weight: 4 },
    'rksqqfr': { weight: 0 },
    'xplsuaq': { weight: 8 },
    'joryloo': { weight: 4 },
    'mxpxa': { weight: 8, children: ['vtjrflg', 'guccv'] },
    'tjcujd': { weight: 3, children: ['cmfit', 'tcvpst'] },
    'wkmey': { weight: 1 },
    'hgkjgm': { weight: 9, children: ['xcjxzq', 'ekffumh', 'juscckl', 'dngqchs'] },
    'vneld': { weight: 2 },
    'lmfchi': { weight: 7, children: ['qnzdaj', 'efqrg', 'murzaw'] },
    'umajdu': { weight: 7 },
    'ierjhuk': { weight: 5 },
    'bvviqc': { weight: 0 },
    'qcizo': { weight: 0 },
    'cwaymbr': { weight: 8 },
    'iemeek': { weight: 7 },
    'lhxdfj': { weight: 2 },
    'nlgoig': { weight: 0, children: ['xyfsr', 'ghuyt', 'ibyvotn'] },
    'xxviu': { weight: 2 },
    'doehwd': { weight: 9, children: ['ahcba', 'pbqdzda', 'xijkpj'] },
    'nzazpe': { weight: 8 },
    'wehfli': { weight: 5, children: ['asuodq', 'fbaiatg'] },
    'athdvrh': { weight: 1, children: ['ajika', 'gxmdnq'] },
    'hwluwdo': { weight: 5 },
    'yvttt': { weight: 1, children: ['fdgccyg', 'joryloo'] },
    'dyxzd': { weight: 6, children: ['gubya', 'pnxmfdc'] },
    'ehoqrji': { weight: 9, children: ['kqvsah', 'yanwn'] },
    'iwdzu': { weight: 8 },
    'owdcg': { weight: 9 },
    'vgaxwnn': { weight: 8 },
    'wlqfnkr': { weight: 7, children: ['wseii', 'axhfcb', 'iomjmn', 'rczoepp'] },
    'jxysad': { weight: 9, children: ['jtydj', 'udkvb', 'plpctjz', 'ydusqh'] },
    'jaedvjj': { weight: 6 },
    'iemgv': { weight: 3 },
    'skjez': { weight: 7, children: ['aivprd', 'cbdyc'] },
    'bwrenq': { weight: 5, children: ['lyaqynn', 'hlcnf'] },
    'hoarkjh': { weight: 2 },
    'tyvhz': { weight: 2, children: ['wjkfdvb', 'powfmo'] },
    'yiyjz': { weight: 1, children: ['ljpeina', 'zzekx'] },
    'fiwnjv': { weight: 5 },
    'dzwnlq': { weight: 4 },
    'algav': { weight: 6 },
    'nhgchm': { weight: 7 },
    'ejoee': { weight: 5, children: ['algav', 'atgamme'] },
    'jncwn': { weight: 4 },
    'gypuu': { weight: 1 },
    'xeiur': { weight: 5 },
    'zqczqd': { weight: 2 },
    'zordz': { weight: 6, children: ['zhubam', 'hoarkjh'] },
    'xtocem': { weight: 3, children: ['ajyzem', 'hqhkw', 'jcshcvr', 'zxbnkvs'] },
    'hhndlt': { weight: 1, children: ['sfxvp', 'ypzqp', 'pewvv'] },
    'rrtpjw': { weight: 8, children: ['ptfyi', 'hgqesr', 'jmdlczf'] },
    'aduuei': { weight: 5 },
    'dzrywb': { weight: 4 },
    'fpnjjy': { weight: 1, children: ['dgqquh', 'ftatt'] },
    'wprhap': { weight: 1 },
    'cvahi': { weight: 9, children: ['auorp', 'jypccpq'] },
    'gxhjjv': { weight: 2 },
    'zbrhqwq': { weight: 1, children: ['kckevg', 'pbcpt'] },
    'rimua': { weight: 6 },
    'fxqaw': { weight: 3, children: ['avfsez', 'tprgqt'] },
    'lyorl': { weight: 0 },
    'csmjw': { weight: 2, children: ['hwluwdo', 'phrrm'] },
    'crqesym': { weight: 5 },
    'gkskqqb': { weight: 3 },
    'cnuygks': { weight: 0 },
    'owxbfr': { weight: 0 },
    'gubya': { weight: 6 },
    'nnjrm': { weight: 9, children: ['nesoknh', 'mkohhbb'] },
    'gjdrco': { weight: 5 },
    'gtditk': { weight: 8 },
    'vlfxdli': { weight: 6 },
    'qwtvro': { weight: 0, children: ['cfiurqp', 'ubdfq', 'xxviu'] },
    'isoayc': { weight: 6 },
    'coicjc': { weight: 5 },
    'yuktpa': { weight: 4 },
    'txnuvci': { weight: 4 },
    'jbomczw': { weight: 2 },
    'jykfxee': { weight: 5 },
    'yyria': { weight: 1, children: ['qztfbzn', 'xfmneu'] },
    'xgibks': { weight: 6, children: ['qvuhbo', 'abspab', 'ehegh', 'bvelsl'] },
    'liklroi': { weight: 8, children: ['xowek', 'qdgsn'] },
    'kdbfv': { weight: 8 },
    'flhhbd': { weight: 1 },
    'halwu': { weight: 6 },
    'enorooc': { weight: 4 },
    'jfnknli': { weight: 5, children: ['hubvoh', 'csmjw', 'kzpyvis', 'hmyuwix', 'fbhxulf'] },
    'yeuaeqp': { weight: 2, children: ['vojcrx', 'jnshvhq'] },
    'plzrspg': { weight: 8, children: ['pdprpyn', 'itacy'] },
    'jcshcvr': { weight: 0 },
    'uckyywt': { weight: 6 },
    'zpyoxs': { weight: 2 },
    'gvujhex': { weight: 9, children: ['jbmxm', 'ozuqsau'] },
    'zxbnkvs': { weight: 0 },
    'ydcibyi': { weight: 1, children: ['sakmn', 'yuktpa', 'ielyzgp'] },
    'ffcefem': { weight: 1 },
    'mxpxbm': { weight: 7, children: ['mvldvib', 'phpjy', 'mtqdya', 'enorooc'] },
    'yzssszb': { weight: 0 },
    'srltg': { weight: 6 },
    'txznlay': { weight: 5 },
    'jwmjagj': { weight: 0 },
    'ejzoa': { weight: 8, children: ['pqqfpa', 'fsqws', 'kqhusg'] },
    'iwtqde': { weight: 7 },
    'tdxsqf': { weight: 1, children: ['ejrychc', 'wqpfc'] },
    'hrqsnls': { weight: 3, children: ['ooobx', 'jfvoui'] },
    'ewgvg': { weight: 3, children: ['sohohlc', 'fxhlrok', 'ykhycl', 'xabull', 'gdvqsyp'] },
    'flgjahm': { weight: 0, children: ['bwhovd', 'zqatt', 'hcqsg'] },
    'odtetse': { weight: 5 },
    'floca': { weight: 8 },
    'jfsnic': { weight: 2 },
    'hdiprgd': { weight: 3 },
    'fwfbd': { weight: 1, children: ['djxvowe', 'mssypcn'] },
    'whfeq': { weight: 6 },
    'lrfttlb': { weight: 3 },
    'aygltsd': { weight: 4 },
    'ztoitoz': { weight: 9 },
    'zooxx': { weight: 0 },
    'cumlar': { weight: 9 },
    'gzarnps': { weight: 5, children: ['mojsngw', 'hybvw', 'ssuho', 'phmoj'] },
    'lpgtx': { weight: 3 },
    'psdhpk': { weight: 0, children: ['ceqayn', 'kimsadh'] },
    'jfvmu': { weight: 4 },
    'hfpspc': { weight: 1 },
    'nghcpr': { weight: 8 },
    'idfuz': { weight: 7, children: ['lwpmgk', 'scfrwrg'] },
    'qqnroz': { weight: 6, children: ['uvexl', 'ldmgzql', 'vtphqb', 'tjcujd'] },
    'tutmv': { weight: 4 },
    'gmaxala': { weight: 3, children: ['yybtd', 'cijhcl'] },
    'kimsadh': { weight: 7 },
    'tbzqsrb': { weight: 3 },
    'ijmaxm': { weight: 2 },
    'biokfm': { weight: 5, children: ['nvflr', 'sabolzl'] },
    'lnllv': { weight: 5, children: ['tpdch', 'nyeur'] },
    'ulpfyrr': { weight: 3 },
    'twjvtbu': { weight: 9 },
    'qkdiej': { weight: 5 },
    'deyxep': { weight: 8 },
    'jbolstg': { weight: 3, children: ['aizud', 'hxowycm', 'fzcerr'] },
    'jvxecw': { weight: 9 },
    'rxwxqe': { weight: 3 },
    'geqrb': { weight: 8 },
    'fytlv': { weight: 5, children: ['pshil', 'bppdgwm'] },
    'lbgqy': { weight: 0 },
    'gmtsea': { weight: 8 },
    'nbvlp': { weight: 7 },
    'vkdpaip': { weight: 0, children: ['xfjpbus', 'ilkhnhw'] },
    'btsvvyg': { weight: 1 },
    'shjlwli': { weight: 4 },
    'uzxjt': { weight: 8 },
    'xichd': { weight: 9 },
    'vhuwgi': { weight: 0 },
    'plmaxee': { weight: 2 },
    'texooeb': { weight: 5 },
    'qneezf': { weight: 3, children: ['bsnxzz', 'yntilqc'] },
    'dzlgor': { weight: 3, children: ['jnmgovh', 'lzqtep', 'umuur', 'nuajwg'] },
    'ubkhce': { weight: 4 },
    'cvxkylq': { weight: 9 },
    'ctqaxh': { weight: 1, children: ['tslfayy', 'xquzvw'] },
    'yfzbdl': { weight: 5, children: ['kmyvyx', 'lyrxhp', 'tuyon', 'rksqqfr'] },
    'rdrrye': { weight: 8 },
    'jrgiha': { weight: 7 },
    'wpugb': { weight: 9, children: ['xhubgcl', 'psdhpk', 'htgvzw', 'shjlwli', 'xtxppp', 'nusvn'] },
    'odmmo': { weight: 6 },
    'hgblqo': { weight: 1 },
    'jcikl': { weight: 9 },
    'khkaq': { weight: 6 },
    'mcmijwy': { weight: 1 },
    'sgymtmx': { weight: 5, children: ['uxbyymt', 'tnngtb'] },
    'fqxrjg': { weight: 5 },
    'rhfznek': { weight: 2, children: ['vckzclh', 'kurnhks', 'ftthnl', 'fseduzt', 'gxumijt'] },
    'txhbij': { weight: 0 },
    'yaann': { weight: 7, children: ['drtfi', 'golkvpd'] },
    'dfolgy': { weight: 0 },
    'qoukeij': { weight: 2, children: ['szdthny', 'bpszadt'] },
    'rmocf': { weight: 0, children: ['fkbivys', 'ryjrq'] },
    'rpxni': { weight: 9 },
    'xmvthbd': { weight: 0 },
    'soddek': { weight: 3, children: ['wragpj', 'qcldyng'] },
    'gwyrxmf': { weight: 3, children: ['ntugl', 'bkqndr', 'nhnwkzo', 'txnuvci'] },
    'bzwiavk': { weight: 2, children: ['vszfxh', 'unbjm', 'hkxefzm', 'vijgqvl'] },
    'okrnkqa': { weight: 0 },
    'pasveb': { weight: 0 },
    'qxivh': { weight: 5 },
    'aakrpyc': { weight: 4 },
    'qfellsp': { weight: 0 },
    'yowbd': { weight: 6, children: ['ooazmvu', 'jtzrvt'] },
    'ielyzgp': { weight: 4 },
    'ihslyyb': { weight: 1 },
    'faubz': { weight: 9 },
    'itacy': { weight: 3 },
    'fwevqj': { weight: 3 },
    'zzsbd': { weight: 8 },
    'edygy': { weight: 8, children: ['yzfnlfl', 'hwdkwn'] },
    'sohswca': { weight: 6 },
    'jngifv': { weight: 4, children: ['rdthc', 'ajdtudl', 'skjez', 'eprljo'] },
    'ivfffiz': { weight: 6, children: ['iqbtc', 'opnpx'] },
    'hcbdbh': { weight: 0, children: ['cibrtjo', 'gkxdmxg'] },
    'rulkpe': { weight: 7, children: ['faubz', 'ftbsur', 'luixm', 'jvxecw'] },
    'fpkuumw': { weight: 1, children: ['arveor', 'hsykei'] },
    'xabull': { weight: 9, children: ['egkqlyz', 'obdtlhg', 'mgoew'] },
    'cvcvyeu': { weight: 0, children: ['rawfw', 'ceywcm'] },
    'wjqdusq': { weight: 6, children: ['odtetse', 'swastze'] },
    'khnemp': { weight: 5 },
    'rudbmkz': { weight: 0 },
    'llbxkj': { weight: 6 },
    'tbfkvty': { weight: 7, children: ['aymgd', 'glmcscm', 'coedb'] },
    'kufceqa': { weight: 5 },
    'exaqlbc': { weight: 6, children: ['tejonrz', 'hlszj'] },
    'hxxexy': { weight: 2 },
    'cveuc': { weight: 7 },
    'pnxmfdc': { weight: 6 },
    'jtwrh': { weight: 3 },
    'pfuyke': { weight: 7, children: ['hsyoiy', 'ovfby'] },
    'wdgfw': { weight: 9 },
    'obdtlhg': { weight: 6, children: ['pbmni', 'gerpefi'] },
    'abdjb': { weight: 5, children: ['nzhfbo', 'begrb'] },
    'onwhg': { weight: 0 },
    'wfixt': { weight: 0 },
    'ngtpz': { weight: 8 },
    'gxumijt': { weight: 7, children: ['yrbwhz', 'yxzdn', 'otslex'] },
    'murzaw': { weight: 4, children: ['cwaymbr', 'iwdzu', 'ouiwlb'] },
    'jtxphqg': { weight: 8, children: ['aakrpyc', 'vjyhqx'] },
    'wjkqpqr': { weight: 5, children: ['auocefh', 'cnuygks', 'nkxdfu', 'rotzn'] },
    'vsvne': { weight: 3, children: ['qkllvda', 'uzxjt'] },
    'jqhify': { weight: 4 },
    'ntadc': { weight: 1 },
    'niuvu': { weight: 1 },
    'bbsvfl': { weight: 6 },
    'powvrta': { weight: 2 },
    'nvflr': { weight: 4 },
    'kebfmsz': { weight: 9, children: ['fhryrfj', 'vxxhu', 'wycfrkz', 'wrurg'] },
    'ueqkrm': { weight: 7 },
    'elyuo': { weight: 5 },
    'kzpyvis': { weight: 4, children: ['akumg', 'dfghz'] },
    'fozgkmk': { weight: 8 },
    'skdbvqr': { weight: 1, children: ['smmdlo', 'cqupm', 'buyazh', 'elxfl'] },
    'pycim': { weight: 5 },
    'spgyst': { weight: 8 },
    'vojcrx': { weight: 7 },
    'xorbfm': { weight: 0, children: ['pwmazwj', 'ztoitoz', 'udiykt'] },
    'wsyiyen': { weight: 4, children: ['cisaxsf', 'rejss', 'zbrhqwq', 'xeiur', 'fyfjc', 'eaxqpmn'] },
    'ivwybv': { weight: 7 },
    'zsjvdo': { weight: 8, children: ['omnyr', 'hrhfd'] },
    'uvfou': { weight: 8, children: ['ygeoklq', 'tzxvnri', 'gufqi'] },
    'objgx': { weight: 0 },
    'zpcqx': { weight: 6, children: ['izxeuz', 'qhwtf'] },
    'emuek': { weight: 9, children: ['tzvtu', 'zzsbd'] },
    'dytadg': { weight: 5 },
    'crdoq': { weight: 2 },
    'lljifba': { weight: 8, children: ['jeywnj', 'fdgjgwt', 'ewgvg', 'mxtcei', 'wetrsmz', 'sgvaf', 'hhndlt'] },
    'hcizj': { weight: 1 },
    'zzkzfln': { weight: 3 },
    'hmjzw': { weight: 7, children: ['aujgtj', 'lshkygc'] },
    'blkcnq': { weight: 1 },
    'udiykt': { weight: 9 },
    'nhnwkzo': { weight: 4 },
    'tiunb': { weight: 6 },
    'ccbgy': { weight: 4 },
    'khjexez': { weight: 9 },
    'tydjgm': { weight: 4 },
    'mssypcn': { weight: 6 },
    'swpjozm': { weight: 6 },
    'yryyz': { weight: 9 },
    'vdham': { weight: 2 },
    'scfrwrg': { weight: 1 },
    'xyfsr': { weight: 5 },
    'golkvpd': { weight: 9 },
    'qovcwth': { weight: 9 },
    'dzngp': { weight: 3, children: ['onwhg', 'xmvthbd'] },
    'vqbfan': { weight: 1 },
    'pkdeoh': { weight: 6 },
    'foozzq': { weight: 4, children: ['klsxgx', 'kcorlw'] },
    'ehegh': { weight: 4 },
    'kqhusg': { weight: 5, children: ['dfolgy', 'yzssszb', 'qfellsp'] },
    'jxzfb': { weight: 8 },
    'airlri': { weight: 7, children: ['pidgnp', 'lljifba', 'gmewl', 'tbedct', 'ryvidhy', 'rdytzgp'] },
    'kreehw': { weight: 7 },
    'zkkjh': { weight: 3 },
    'vqlyyx': { weight: 3 },
    'mkbjgur': { weight: 4 },
    'faqsp': { weight: 0 },
    'fiqnz': { weight: 2 },
    'esyzn': { weight: 6 },
    'swastze': { weight: 5 },
    'wbiys': { weight: 8 },
    'xiyhl': { weight: 9, children: ['ktvry', 'ezoar'] },
    'aonpvtr': { weight: 2 },
    'pgibhk': { weight: 5 },
    'axgpt': { weight: 3 },
    'kxqhlbm': { weight: 1, children: ['sulyr', 'qeksx'] },
    'apgqnys': { weight: 2 },
    'osipmuv': { weight: 6, children: ['qkaaq', 'ffrgif', 'qxvpdh'] },
    'lzqtep': { weight: 6 },
    'jrjkj': { weight: 9 },
    'omnyr': { weight: 7 },
    'jmdlczf': { weight: 2, children: ['idfuz', 'xichd', 'pkuqykh', 'xpzadg', 'kioxu', 'huzzk', 'vgrbrzc'] },
    'vvivo': { weight: 0 },
    'uents': { weight: 7 },
    'utprdt': { weight: 3, children: ['ihslyyb', 'knhati'] },
    'lcqed': { weight: 5 },
    'vnyaqgw': { weight: 0 },
    'szdthny': { weight: 5 },
    'rwqopie': { weight: 5 },
    'vgrbrzc': { weight: 1, children: ['swpjozm', 'ibdon', 'sohswca'] },
    'spjim': { weight: 3 },
    'bipyp': { weight: 8 },
    'mvxqfe': { weight: 5 },
    'vlszzu': { weight: 3, children: ['nafvoj', 'foozzq', 'jgwajk', 'ppedet', 'hqpkdyb'] },
    'jdrkeh': { weight: 5 },
    'ftbsur': { weight: 9 },
    'uldlh': { weight: 0 },
    'dzbnx': { weight: 7 },
    'vswgxoh': { weight: 3, children: ['obilnz', 'zkkjh', 'ulpfyrr'] },
    'xbowtoi': { weight: 3, children: ['tdbwpcj', 'muecxv'] },
    'mysjwy': { weight: 2 },
    'tetyj': { weight: 5, children: ['xckaw', 'tadprtr'] },
    'pbqdzda': { weight: 8 },
    'gahwap': { weight: 5 },
    'vjyhqx': { weight: 4 },
    'aywrlw': { weight: 2, children: ['xxvfb', 'bmxoqy'] },
    'zgzxr': { weight: 5, children: ['ewvlay', 'slclu'] },
    'jgwajk': { weight: 4, children: ['fdyuo', 'keoqd'] },
    'powfmo': { weight: 0 },
    'auorp': { weight: 6 },
    'jtydj': { weight: 2, children: ['rpsmo', 'lbgqy'] },
    'iomjmn': { weight: 6 },
    'slclu': { weight: 4 },
    'isvfa': { weight: 5 },
    'mhcyj': { weight: 1, children: ['gxhjjv', 'ipppjn'] },
    'rpsmo': { weight: 0 },
    'flbumzk': { weight: 6 },
    'xtxppp': { weight: 2, children: ['miidkpe', 'srltg'] },
    'vpsls': { weight: 6 },
    'hlansqa': { weight: 3 },
    'znbvji': { weight: 4 },
    'kieild': { weight: 3 },
    'klsxgx': { weight: 6 },
    'asuodq': { weight: 3 },
    'tuuzrr': { weight: 8 },
    'xckaw': { weight: 0 },
    'efqrg': { weight: 2, children: ['vgaxwnn', 'opbrn'] },
    'ibagnjs': { weight: 9 },
    'vyevfn': { weight: 0, children: ['jtwrh', 'kieild', 'gmevoe'] },
    'kvyiqr': { weight: 5, children: ['kvypj', 'hcizj'] },
    'qghotl': { weight: 2 },
    'pzywvr': { weight: 2, children: ['txswi', 'jljgd', 'hxxexy', 'apgqnys'] },
    'akmsaq': { weight: 7 },
    'mhseysh': { weight: 9 },
    'uarsqn': { weight: 3 },
    'ryvidhy': { weight: 1, children: ['pxnvwaj', 'skdbvqr', 'qhdqak'] },
    'cqdggj': { weight: 6, children: ['efkyht', 'gtgdmny', 'ohbzmqz'] },
    'ykoazai': { weight: 8 },
    'sydiov': { weight: 7, children: ['xvhpqmh', 'exaex', 'utprdt'] },
    'algetkl': { weight: 3 },
    'hbldvzk': { weight: 8, children: ['sydiov', 'ropjtoe', 'rhfznek'] },
    'pzggi': { weight: 9, children: ['efbvz', 'dzwnlq'] },
    'rnfoji': { weight: 6 },
    'ytfnug': { weight: 9 },
    'jpxgvjl': { weight: 2 },
    'yotrh': { weight: 8 },
    'xpqnuh': { weight: 1 },
    'ewuohku': { weight: 8 },
    'vlllp': { weight: 5 },
    'erpdg': { weight: 4, children: ['rdnozh', 'plzrspg', 'tirehn'] },
    'ablgyqv': { weight: 8 },
    'yqxvhbl': { weight: 2 },
    'hgrjt': { weight: 8 },
    'joees': { weight: 3 },
    'eqsqenp': { weight: 6 },
    'mnxmtp': { weight: 5 },
    'wetrsmz': { weight: 4, children: ['wpfywy', 'litnjrv', 'rpmtne'] },
    'bkicgcc': { weight: 3 },
    'dwvbnp': { weight: 0 },
    'qptzj': { weight: 6 },
    'ibvyfys': { weight: 0, children: ['rpzit', 'bepnzsh', 'khjexez'] },
    'bwhovd': { weight: 7, children: ['yhgutqw', 'amhmm', 'cwdfqo', 'vlaowv', 'vkdpaip', 'tyvhz', 'unqmapv'] },
    'fyfjc': { weight: 1, children: ['qghotl', 'jbomczw'] },
    'zaiopar': { weight: 0 },
    'rimobjs': { weight: 8 },
    'ipfmr': { weight: 1, children: ['mkvblbi', 'btrdhk'] },
    'mbslas': { weight: 1 },
    'zkwplas': { weight: 3, children: ['tdxsqf', 'gzarnps', 'nujmyt'] },
    'hoilkqz': { weight: 4 },
    'jljgd': { weight: 2 },
    'wfwma': { weight: 5 },
    'rfeqsq': { weight: 7 },
    'ptfyi': { weight: 9, children: ['exaqlbc', 'vdham', 'vxjvov'] },
    'jdtwus': { weight: 5, children: ['cumlar', 'rpxni'] },
    'ddrsd': { weight: 9, children: ['aibabp', 'dweli'] },
    'buyou': { weight: 0 },
    'plrma': { weight: 4 },
    'cmfit': { weight: 2 },
    'nbjrv': { weight: 9 },
    'aizud': { weight: 8, children: ['eirze', 'xnoux'] },
    'jgbvdp': { weight: 1, children: ['pasveb', 'vhcza'] },
    'vckzclh': { weight: 0, children: ['vuzkop', 'gpgmx'] },
    'xdzya': { weight: 9, children: ['malnjq', 'jircuj', 'zxdfpy'] },
    'zfaxas': { weight: 0 },
    'keoqd': { weight: 1 },
    'xnqeu': { weight: 0 },
    'wycfrkz': { weight: 2 },
    'oidjn': { weight: 8 },
    'ihmqbiu': { weight: 5, children: ['hcbdbh', 'abicjs', 'rpiuf', 'zpcqx', 'pzywvr'] },
    'rpiuf': { weight: 2, children: ['znbvji', 'rjjeggt'] },
    'ygykyu': { weight: 5 },
    'abicjs': { weight: 5, children: ['ierjhuk', 'psmvz', 'nfkbhas'] },
    'ehclf': { weight: 0 },
    'okmwjoa': { weight: 2 },
    'uxbyymt': { weight: 2 },
    'xqyrozn': { weight: 7 },
    'eaxqpmn': { weight: 9, children: ['zagaz', 'tzobgt'] },
    'undug': { weight: 8 },
    'uxrros': { weight: 9, children: ['kebfmsz', 'sqnfn', 'mlztke', 'ibvyfys', 'facjth', 'soddek', 'kxsefnd'] },
    'rlyxbi': { weight: 3, children: ['qrrdb', 'vvpacb', 'klcuumi', 'etxfihy', 'tptxpuq'] },
    'vmgxg': { weight: 2, children: ['coicjc', 'dpqrxbr', 'mhcyj', 'pzmmc'] },
    'xoabt': { weight: 8 },
    'qztfbzn': { weight: 9 },
    'jbmxm': { weight: 8 },
    'noqmsh': { weight: 1 },
    'pgujeq': { weight: 5, children: ['fiqnz', 'msywua'] },
    'gmewl': { weight: 3, children: ['sxpee', 'flgjahm', 'hrbukg', 'rrtpjw', 'hgkjgm', 'twxwam', 'xdzya'] },
    'pnszexz': { weight: 3, children: ['ycxyxg', 'ycnnc'] },
    'aledrs': { weight: 3 },
    'rwouyb': { weight: 4 },
    'uuztubk': { weight: 9, children: ['rxbrsd', 'hwekwoq', 'ffzjjj'] },
    'uwojoup': { weight: 0 },
    'svlvlj': { weight: 4, children: ['pqsfee', 'fguhavr'] },
    'ykzjkp': { weight: 6 },
    'vfrna': { weight: 2, children: ['dhsyxu', 'dytadg', 'gjihp'] },
    'vimplcz': { weight: 1 },
    'cwppzzd': { weight: 8 },
    'bstqyq': { weight: 5 },
    'mtqdya': { weight: 4 },
    'enmoyyj': { weight: 0 },
    'lfqtv': { weight: 0, children: ['lnllv', 'gelep', 'lwujegj', 'uowiif'] },
    'aujgtj': { weight: 9 },
    'hdyrxg': { weight: 6 },
    'ezoar': { weight: 2 },
    'zkkvh': { weight: 4 },
    'ylmwjuo': { weight: 5 },
    'mdanw': { weight: 1 },
    'klhzgvj': { weight: 7, children: ['qmsxr', 'wuluf'] },
    'rpmtne': { weight: 8, children: ['heezga', 'xuwmc', 'rdrrye', 'qyvxs', 'sppxgv'] },
    'zozajw': { weight: 9, children: ['esyzn', 'vlfxdli'] },
    'drfzng': { weight: 8, children: ['hmwfqwz', 'zelwp', 'pgujeq', 'gzqutgv'] },
    'hzauzw': { weight: 5, children: ['hgrjt', 'tuuzrr'] },
    'aepss': { weight: 6 },
    'zkaqnra': { weight: 0, children: ['upndyov', 'mcnsxuh', 'rulkpe', 'pfuyke', 'dzngp'] },
    'egtem': { weight: 6 },
    'reuaanp': { weight: 5 },
    'apexe': { weight: 5, children: ['pkjykh', 'wupsg', 'kdrke'] },
    'agmao': { weight: 3 },
    'ctdsj': { weight: 8 },
    'izkej': { weight: 8 },
    'wfpxk': { weight: 0 },
    'cmqni': { weight: 6 },
    'qoksme': { weight: 1, children: ['algetkl', 'xhqrf'] },
    'otslex': { weight: 9 },
    'vumpiw': { weight: 9, children: ['uwoyjsd', 'xdwrl'] },
    'zimidd': { weight: 1, children: ['hcrxqbw', 'uwojoup'] },
    'eegwdp': { weight: 2 },
    'pjssvle': { weight: 2 },
    'zbtswr': { weight: 4 },
    'dzugjhb': { weight: 0, children: ['orxgo', 'irgymg', 'cvxkylq', 'svfgh'] },
    'befsr': { weight: 0 },
    'lrhkoc': { weight: 2 },
    'cbaah': { weight: 5 },
    'cimubay': { weight: 2 },
    'vnuwoq': { weight: 5 },
    'vbzyp': { weight: 7 },
    'exaex': { weight: 5 },
    'nmvki': { weight: 0 },
    'xdwrl': { weight: 3 },
    'gmfsl': { weight: 6, children: ['yktmvtf', 'auztp', 'vhlizib'] },
    'wsyqwf': { weight: 2 },
    'phdetz': { weight: 5 },
    'krquje': { weight: 1 },
    'vyqlzi': { weight: 1, children: ['wnqny', 'hwhhyhh'] },
    'qmsxr': { weight: 2 },
    'ojzpzsa': { weight: 0 },
    'qvuhbo': { weight: 4 },
    'esegn': { weight: 6 },
    'bdqnomo': { weight: 0 },
    'tgexl': { weight: 6 },
    'nuvrtnk': { weight: 9 },
    'zarww': { weight: 2, children: ['vrqdv', 'ojozup'] },
    'qqmpq': { weight: 1, children: ['dxggcx', 'kazlt', 'elcnwtn'] },
    'pgdgh': { weight: 2, children: ['uzoroj', 'yaann', 'pnszexz'] },
    'walzh': { weight: 7, children: ['nbvlp', 'suyawzr'] },
    'kkjro': { weight: 2, children: ['vyfhcqp', 'yiyjz', 'nnjrm', 'oojlo', 'fdhvp'] },
    'sxpee': { weight: 1, children: ['sppgjfx', 'qwlze', 'erpdg', 'xngnhi', 'jngifv', 'jjxhgkx', 'lfqtv'] },
    'jnshvhq': { weight: 7 },
    'ppavww': { weight: 2 },
    'vljooo': { weight: 6 },
    'zdaorg': { weight: 2 },
    'hlcnf': { weight: 3 },
    'mzgayzs': { weight: 4, children: ['hpsljy', 'rgpazuy', 'wjqdusq', 'cvcvyeu', 'qfzyvjr', 'euxrv', 'xfkpfqd'] },
    'dfntl': { weight: 4 },
    'efijtd': { weight: 5 },
    'sqcet': { weight: 3 },
    'malnjq': { weight: 0, children: ['xqrnd', 'jrygk', 'qoukeij', 'hmtnj'] },
    'ktvry': { weight: 2 },
    'fkvhdj': { weight: 1 },
    'qtcsae': { weight: 5 },
    'uwpuqd': { weight: 6 },
    'oeehfxg': { weight: 5 },
    'nfchpk': { weight: 7, children: ['amooqlb', 'rxwxqe', 'uarsqn'] },
    'hykmnhl': { weight: 2 },
    'tadprtr': { weight: 0 },
    'kqfesp': { weight: 2 },
    'piofa': { weight: 6, children: ['mxpxa', 'jbkek', 'cqupq'] },
    'fseduzt': { weight: 4, children: ['cbacfi', 'ypeap', 'vvivo'] },
    'moeujf': { weight: 1, children: ['bkfbj', 'apajk'] },
    'vlysce': { weight: 8 },
    'xowek': { weight: 7 },
    'cqfyjm': { weight: 8 },
    'nzhfbo': { weight: 6 },
    'ovfby': { weight: 3 },
    'nkxdfu': { weight: 0 },
    'ooazmvu': { weight: 5 },
    'qrmipn': { weight: 7 },
    'wragpj': { weight: 2 },
    'bgasdfq': { weight: 8, children: ['zxphdt', 'jdrkeh'] },
    'srcfgoo': { weight: 9, children: ['tetyj', 'qdfzlv', 'gymuodz', 'qbnldp'] },
    'hztzf': { weight: 2, children: ['spgyst', 'jxzfb'] },
    'ebzton': { weight: 4 },
    'imdqhns': { weight: 5 },
    'tejonrz': { weight: 3 },
    'yvpzbgp': { weight: 4 },
    'luviddq': { weight: 1 },
    'akumg': { weight: 4 },
    'ixwoprg': { weight: 2, children: ['zpyoxs', 'wwkdvm'] },
    'uowiif': { weight: 6, children: ['luviddq', 'jhltpk', 'dtsdw'] },
    'zznnz': { weight: 8 },
    'dnmsps': { weight: 1, children: ['plrma', 'jqhify'] },
    'wfkxhlf': { weight: 2 },
    'yyrwb': { weight: 5 },
    'kdwict': { weight: 7, children: ['umajdu', 'hgogzfl'] },
    'gpgmx': { weight: 7 },
    'mzjhsq': { weight: 2 },
    'cxgdzl': { weight: 7, children: ['glumdc', 'unnvung', 'ccbgy', 'zgrcahy'] },
    'knendm': { weight: 9, children: ['jaedvjj', 'poviv'] },
    'xymtys': { weight: 4, children: ['ayfafvc', 'ywrze'] },
    'xrmslfs': { weight: 4 },
    'ycnnc': { weight: 1 },
    'plpctjz': { weight: 6, children: ['cwppzzd', 'taaoji'] },
    'qazqwkj': { weight: 0 },
    'swqgxh': { weight: 6 },
    'phmoj': { weight: 2 },
    'knmmys': { weight: 0, children: ['pyhohkx', 'xiyhl', 'jdtwus', 'fwfbd'] },
    'vcrgmn': { weight: 7, children: ['zhnug', 'rfeqsq'] },
    'cibrtjo': { weight: 0 },
    'kkjnouk': { weight: 9, children: ['tbfkvty', 'vaqhekv', 'zbxopzp', 'biokfm'] },
    'bpmus': { weight: 7 },
    'yntilqc': { weight: 5 },
    'ejrychc': { weight: 6 },
    'nusvn': { weight: 4, children: ['kqokslj', 'owxbfr'] },
    'begrb': { weight: 6 },
    'axhfcb': { weight: 6 },
    'lgmjeng': { weight: 5 },
    'kqfob': { weight: 5 },
    'qqfgo': { weight: 5 },
    'fsose': { weight: 1, children: ['tmpysyn', 'hsjbzgd'] },
    'hospabk': { weight: 3 },
    'cvxcr': { weight: 3 },
    'nefpbc': { weight: 4 },
    'dpcuy': { weight: 8 },
    'zsratan': { weight: 9 },
    'gybbvb': { weight: 7 },
    'tbedct': { weight: 6, children: ['ydcibyi', 'ejzoa', 'lcbkylu', 'wpugb', 'rlyxbi', 'jbolstg'] },
    'wpxhphx': { weight: 6, children: ['otnrfom', 'iemeek'] },
    'xjiql': { weight: 4, children: ['mplgqv', 'rrxrsx'] },
    'kurnhks': { weight: 4, children: ['zlsrhdz', 'pgibhk', 'zsancei', 'crqesym'] },
    'fknai': { weight: 6 },
    'abccyo': { weight: 8 },
    'jaxjy': { weight: 9 },
    'zxdfpy': { weight: 9, children: ['ikeiwjo', 'qwfosq', 'mmotdue', 'hjkrxly', 'zttytvi', 'swjcx', 'kvheuf'] },
    'cgetpc': { weight: 3 },
    'wwrkqb': { weight: 5, children: ['ruhqq', 'jrgiha'] },
    'sfrwf': { weight: 7 },
    'qjxyfa': { weight: 1 },
    'vhlizib': { weight: 7 },
    'hwekwoq': { weight: 8 },
    'mocrsqu': { weight: 9, children: ['vqlyyx', 'wdnlqh', 'apbjfv'] },
    'mevce': { weight: 8 },
    'yldsmt': { weight: 7 },
    'wwkdvm': { weight: 2 },
    'reqlm': { weight: 1 },
    'pdprpyn': { weight: 3 },
    'irgumpr': { weight: 1, children: ['xgibks', 'eowjgp', 'bzwiavk', 'cgtddkw', 'tinitt', 'cnrwew'] },
    'jjdfk': { weight: 3 },
    'lmtebyt': { weight: 5 },
    'ibdon': { weight: 6 },
    'jjvbyf': { weight: 2 },
    'ncffht': { weight: 7 },
    'hpsljy': { weight: 6, children: ['cukfipr', 'nqomdre'] },
    'wqpfc': { weight: 6 },
    'glmcscm': { weight: 2 },
    'mitvkt': { weight: 7, children: ['dlapc', 'eqsqenp'] },
    'kmemzft': { weight: 1 },
    'gqwfi': { weight: 1 },
    'lhmhrpi': { weight: 5 },
    'tirehn': { weight: 0, children: ['bdlzzvy', 'jnyvdz', 'zkwzctg'] },
    'tmsnmf': { weight: 2 },
    'lxxbgm': { weight: 6, children: ['hlansqa', 'agmao', 'dihvt', 'uxgux'] },
    'yhonqw': { weight: 9, children: ['tcaex', 'nwlacty', 'gkzpb', 'qtjpthc', 'ipfmr'] },
    'oedan': { weight: 1, children: ['zntrkc', 'lwpwtbj', 'awvqy', 'mmomd'] },
    'gelep': { weight: 4, children: ['qxivh', 'lmtebyt', 'wfwma'] },
    'fllao': { weight: 4 },
    'sabolzl': { weight: 4 },
    'tmpysyn': { weight: 2 },
    'wrurg': { weight: 2 },
    'sfuegcs': { weight: 2 },
    'bhqkvi': { weight: 1 },
    'qgkaso': { weight: 8 },
    'fhryrfj': { weight: 2 },
    'hjkrxly': { weight: 7, children: ['texooeb', 'elyuo'] },
    'ssuho': { weight: 2 },
    'rejss': { weight: 9, children: ['powvrta', 'fojnd', 'otqdauw'] },
    'ffzjjj': { weight: 8 },
    'qkaaq': { weight: 0 },
    'suvwi': { weight: 9 },
    'rczoepp': { weight: 6 },
    'bhzeep': { weight: 0 },
    'kkflx': { weight: 0, children: ['coazy', 'kdwict', 'ojcpgj', 'qjdqn'] },
    'gkxdmxg': { weight: 0 },
    'upnls': { weight: 8 },
    'bepnzsh': { weight: 9 },
    'xxsobt': { weight: 7, children: ['zznnz', 'ziyta', 'xypex'] },
    'bgscxgk': { weight: 5 },
    'tptxpuq': { weight: 4, children: ['kemme', 'vfmiaz'] },
    'qummd': { weight: 7 },
    'efkyht': { weight: 1 },
    'mmomd': { weight: 1 },
    'sulyr': { weight: 3 },
    'txswi': { weight: 2 },
    'ksbjftc': { weight: 5, children: ['gfghu', 'spjim'] },
    'gjvfc': { weight: 4 },
    'egkqlyz': { weight: 8, children: ['vlysce', 'fozgkmk'] },
    'aqeqvr': { weight: 6 },
    'kvheuf': { weight: 3, children: ['johqe', 'dyeds'] },
    'ajika': { weight: 2 },
    'dihvt': { weight: 3 },
    'zmpyqv': { weight: 6 },
    'xxvfb': { weight: 7 },
    'fvmws': { weight: 3 },
    'hsjbzgd': { weight: 2 },
    'uyvuqp': { weight: 9, children: ['dfntl', 'jfvmu'] },
    'cvseh': { weight: 3, children: ['liklroi', 'zsjvdo', 'bwtsue'] },
    'juscckl': { weight: 9, children: ['svlvlj', 'bujphvu', 'bgasdfq', 'ctdcrl'] },
    'ruhqq': { weight: 7 },
    'yekxli': { weight: 1 },
    'ywrze': { weight: 3 },
    'jrksg': { weight: 8 },
    'mkvblbi': { weight: 3 },
    'suyawzr': { weight: 7 },
    'yhgutqw': { weight: 0, children: ['oybow', 'ctdsj', 'deyxep', 'iyegmn'] },
    'qucxsqh': { weight: 3 },
    'iurmaj': { weight: 0 },
    'ejjgym': { weight: 9 },
    'jfajopz': { weight: 6, children: ['aonpvtr', 'hykmnhl', 'ppavww', 'wfkxhlf'] },
    'undaxyj': { weight: 2 },
    'avfsez': { weight: 1 },
    'gbqig': { weight: 1, children: ['qgkaso', 'gtditk'] },
    'qaqof': { weight: 0, children: ['oxerrb', 'afxazvx', 'mhseysh'] },
    'xdrjmkv': { weight: 2 },
    'tocdoo': { weight: 2 },
    'mlztke': { weight: 3, children: ['bgjwy', 'lrosl'] },
    'aymgd': { weight: 2 },
    'mcnsxuh': { weight: 3, children: ['xnqeu', 'xrjrjp', 'qvowcc', 'qazqwkj'] },
    'afycii': { weight: 9, children: ['okqwb', 'mvxqfe'] },
    'atzuayu': { weight: 1 },
    'svfgh': { weight: 9 },
    'tnngtb': { weight: 2 },
    'hwhhyhh': { weight: 6 },
    'qrlmd': { weight: 8, children: ['xernf', 'klvhv'] },
    'wnjtvt': { weight: 1 },
    'wzruwk': { weight: 2 },
    'luixm': { weight: 9 },
    'hkntpfd': { weight: 7, children: ['pyraep', 'tiunb'] },
    'mqjpes': { weight: 2 },
    'pshil': { weight: 8 },
    'wvisr': { weight: 7, children: ['znkqj', 'dwvbnp'] },
    'slohro': { weight: 8, children: ['qhgvoj', 'mdanw', 'zimidd'] },
    'rdnozh': { weight: 4, children: ['lgmjeng', 'llalv'] },
    'psmvz': { weight: 5 },
    'zlsrhdz': { weight: 5 },
    'taaoji': { weight: 8 },
    'wbqkf': { weight: 2 },
    'metsfo': { weight: 3, children: ['xoabt', 'wbiys'] },
    'kckevg': { weight: 7 },
    'hhrlaah': { weight: 5, children: ['smjtypd', 'rwqopie'] },
    'daesbhs': { weight: 7 },
    'tuyjnby': { weight: 4 },
    'danfue': { weight: 2, children: ['okrnkqa', 'mqjqez', 'gndjq', 'qcizo'] },
    'ropjtoe': { weight: 2, children: ['wpxhphx', 'wrwusvc', 'zarww', 'xymtys'] },
    'tinitt': { weight: 0, children: ['gypuu', 'btsvvyg'] },
    'kxsefnd': { weight: 5, children: ['cmqni', 'pjhoue'] },
    'yzfnlfl': { weight: 7 },
    'wpfywy': { weight: 0, children: ['mifmz', 'edygy', 'nmfhgq', 'danfue'] },
    'hwldx': { weight: 6 },
    'sakmn': { weight: 4 },
    'ehlwoxs': { weight: 4, children: ['qggjzz', 'zordz', 'phntkf'] },
    'fekdmb': { weight: 6 },
    'ziyta': { weight: 8 },
    'cbdyc': { weight: 8 },
    'ibushn': { weight: 1, children: ['thats', 'nefpbc', 'yvpzbgp', 'vddsv'] },
    'lcbkylu': { weight: 2, children: ['gawbtev', 'aejhrrh', 'zfzpgfw'] },
    'mhlgi': { weight: 0 },
    'rptfwu': { weight: 2 },
    'fkmyndg': { weight: 0 },
    'tylelk': { weight: 4, children: ['drfzng', 'yhonqw', 'wsyiyen', 'dqwocyn', 'qqnroz'] },
    'azjunml': { weight: 2 },
    'hfjazyf': { weight: 0 },
    'nuajwg': { weight: 6 },
    'cukfipr': { weight: 0 },
    'pkcpn': { weight: 0 },
    'guccv': { weight: 3 },
    'pyfeav': { weight: 2 },
    'ikeiwjo': { weight: 7 },
    'hqcwl': { weight: 9 },
    'xayhv': { weight: 6 },
    'wemzz': { weight: 6 },
    'cqupq': { weight: 8, children: ['jjvbyf', 'zddlo', 'plmaxee'] },
    'btrdhk': { weight: 3 },
    'eirze': { weight: 1 },
    'litnjrv': { weight: 3, children: ['fxqaw', 'jbqehvt', 'hhrlaah'] },
    'gveca': { weight: 6, children: ['bstqyq', 'imdqhns'] },
    'wpgziu': { weight: 8 },
    'vfwwc': { weight: 1, children: ['anoza', 'zjhnhz', 'hgdghys'] },
    'losjvw': { weight: 1 },
    'zbxopzp': { weight: 7, children: ['qaqgap', 'cqfyjm'] },
    'uksim': { weight: 4 },
    'uiiqr': { weight: 1, children: ['ysxuvi', 'yryyz', 'dnmsps', 'cqdggj', 'vyevfn', 'dzienj'] },
    'mifmz': { weight: 0, children: ['tgqxadm', 'efqzxka'] },
    'hkxefzm': { weight: 0 },
    'ojcpgj': { weight: 1, children: ['fpwoels', 'dzyfjvd'] },
    'xqrnd': { weight: 5, children: ['wlodh', 'gbmexj', 'zsratan'] },
    'ahcba': { weight: 8 },
    'jnxbxzk': { weight: 2 },
    'ftthnl': { weight: 2, children: ['halwu', 'mdktwy'] },
    'qjlrpjn': { weight: 9 },
    'nuwpvd': { weight: 6 },
    'jnhyc': { weight: 2, children: ['lcqed', 'fiwnjv'] },
    'gmevoe': { weight: 3 },
    'glumdc': { weight: 4 },
    'rajiodp': { weight: 8, children: ['uldlh', 'rudbmkz'] },
    'qebkt': { weight: 5 },
    'vddfzu': { weight: 7, children: ['wchtkp', 'aduuei'] },
    'hcqsg': { weight: 9, children: ['zgzxr', 'moeujf', 'xtocem', 'hivsxt'] },
    'wrwusvc': { weight: 0, children: ['bdqnomo', 'objgx'] },
    'uzoroj': { weight: 9, children: ['dvips', 'dkeosz'] },
    'ujyxvl': { weight: 4 },
    'nltqkvf': { weight: 6, children: ['fwevqj', 'aledrs', 'elvzp'] },
    'lhjpci': { weight: 4 },
    'igqup': { weight: 9 },
    'vszfxh': { weight: 0 },
    'ztxjb': { weight: 1 },
    'aibabp': { weight: 8 },
    'vaqhekv': { weight: 7, children: ['pejkmud', 'bkicgcc'] },
    'wchtkp': { weight: 5 },
    'ycxyxg': { weight: 1 },
    'rgpazuy': { weight: 4, children: ['waxvx', 'uckyywt'] },
    'bppdgwm': { weight: 8 },
    'csxdpl': { weight: 6 },
    'vxjvov': { weight: 8, children: ['tocdoo', 'jpxgvjl'] },
    'vuckhv': { weight: 7 },
    'wnqny': { weight: 6 },
    'kcorlw': { weight: 6 },
    'jlvakq': { weight: 9, children: ['ngtpz', 'xplsuaq'] },
    'tcfmra': { weight: 6 },
    'twxwam': { weight: 5, children: ['qwtvro', 'osipmuv', 'cldldxp'] },
    'xhang': { weight: 8 },
    'qneggdm': { weight: 9, children: ['iurmaj', 'faqsp'] },
    'umuur': { weight: 6 },
    'tuyon': { weight: 0 },
    'aqoik': { weight: 3 },
    'oldoxo': { weight: 5 },
    'rjjeggt': { weight: 4 },
    'fdklcbu': { weight: 0 },
    'tslfayy': { weight: 1 },
    'zpjju': { weight: 8, children: ['ncffht', 'akmsaq'] },
    'xijkpj': { weight: 8 },
    'xfmneu': { weight: 9 },
    'fdgccyg': { weight: 4 },
    'qkllvda': { weight: 8 },
    'zhubam': { weight: 2 },
    'emreip': { weight: 4 },
    'euypgtx': { weight: 0 },
    'tbwieh': { weight: 8, children: ['uglla', 'iyqcty', 'pgtmio'] },
    'mlkddpw': { weight: 4 },
    'zxphdt': { weight: 5 },
    'ohbzmqz': { weight: 1 },
    'dylrpo': { weight: 9 },
    'zjuupn': { weight: 1, children: ['sibko', 'mlighq', 'wogrc'] },
    'xykvys': { weight: 0, children: ['iemgv', 'joees'] },
    'nxwtdg': { weight: 1, children: ['tcfmra', 'nvkhow', 'fekdmb', 'xgufltj'] },
    'mlighq': { weight: 7 },
    'abspab': { weight: 4 },
    'fzcerr': { weight: 0, children: ['zhnjnvg', 'bncmd'] },
    'fxhlrok': { weight: 9, children: ['dyxzd', 'rajiodp', 'hztzf', 'apexe'] },
    'xvhpqmh': { weight: 7, children: ['tuyjnby', 'aygltsd'] },
    'nafvoj': { weight: 7, children: ['aqoik', 'tapirho', 'kyizmdu'] },
    'bkfbj': { weight: 1 },
    'hmyuwix': { weight: 0, children: ['bpmrgr', 'soiza', 'mkbjgur'] },
    'ilkhnhw': { weight: 6 },
    'fkbivys': { weight: 9 },
    'ikclk': { weight: 7 },
    'ysxuvi': { weight: 9 },
    'sppgjfx': { weight: 0, children: ['bszaj', 'ozzxjr', 'ivfffiz', 'cdqkuuw'] },
    'dfghz': { weight: 4 },
    'bxwtlj': { weight: 4, children: ['khkaq', 'pkdeoh', 'dvvlx'] },
    'uvexl': { weight: 5, children: ['ftohrkw', 'fknai'] },
    'xrjrjp': { weight: 0 },
    'oopiw': { weight: 4 },
    'yesozb': { weight: 5 },
    'wochkc': { weight: 8 },
    'dzyfjvd': { weight: 5 },
    'efqzxka': { weight: 1 },
    'hdjlp': { weight: 5 },
    'pbmni': { weight: 9 },
    'afcsq': { weight: 0, children: ['zlvgiq', 'wemzz'] },
    'hsykei': { weight: 0 },
    'swjcx': { weight: 9, children: ['nbjrv', 'ytfnug'] },
    'yanwn': { weight: 5 },
    'orxgo': { weight: 9 },
    'tcvpst': { weight: 2 },
    'xnfybs': { weight: 1 },
    'ctqym': { weight: 9 },
    'hwdkwn': { weight: 7 },
    'bvelsl': { weight: 4 },
    'gkegoh': { weight: 1 },
    'cbacfi': { weight: 0 },
    'gjihp': { weight: 5 },
    'hgdghys': { weight: 8, children: ['acpwe', 'yvttt', 'xbowtoi', 'hmrrarb', 'qneggdm'] },
    'aejhrrh': { weight: 1, children: ['gkskqqb', 'acgiwii'] },
    'pzmmc': { weight: 3, children: ['kmemzft', 'ewtqg'] },
    'ffrgif': { weight: 6, children: ['bpmus', 'vuckhv'] },
    'naacbhr': { weight: 9 },
    'qeksx': { weight: 3 },
    'ncymzc': { weight: 2, children: ['holcno', 'lmueep'] },
    'gfghu': { weight: 3 },
    'qbncqqm': { weight: 6 },
    'qqkwjoy': { weight: 7, children: ['iuagzo', 'nuvrtnk'] },
    'sohohlc': { weight: 7, children: ['gmeqmy', 'xstgov', 'ncymzc'] },
    'zhnjnvg': { weight: 5 },
    'blstaec': { weight: 5, children: ['kxcid', 'qummd'] },
    'uhmmouc': { weight: 4 },
    'tfphsaq': { weight: 5, children: ['sndfkkd', 'vddfzu', 'xorbfm'] },
    'phntkf': { weight: 1, children: ['jjdfk', 'sqcet', 'iueqa'] },
    'xfkpfqd': { weight: 6 },
    'tujrz': { weight: 2 },
    'sfxvp': { weight: 7, children: ['uvfou', 'kasozsw', 'jfajopz'] },
    'lyaqynn': { weight: 3 },
    'bfqotji': { weight: 5 },
    'jbkek': { weight: 4, children: ['txznlay', 'fkzxmb'] },
    'kqvsah': { weight: 5 },
    'zffoytm': { weight: 5 },
    'bpvit': { weight: 4, children: ['tgexl', 'qbncqqm'] },
    'ocuhfpd': { weight: 5 },
    'xhqrf': { weight: 3 },
    'jtgcmc': { weight: 7, children: ['aqfemi', 'undug', 'bpznnqh', 'mmjpziu'] },
    'rdthc': { weight: 3, children: ['zfaxas', 'wfpxk', 'jwmjagj'] },
    'hrbukg': { weight: 4, children: ['vlszzu', 'irgumpr', 'xwunxz'] },
    'sndfkkd': { weight: 3, children: ['yldsmt', 'drswab'] },
    'znkqj': { weight: 0 },
    'xhubgcl': { weight: 4, children: ['xnqznos', 'cbaah'] },
    'epeain': { weight: 6 },
    'jbqehvt': { weight: 5 },
    'dobqmg': { weight: 9, children: ['ejjgym', 'igqup'] },
    'fguhavr': { weight: 2 },
    'dtakrnu': { weight: 0 },
    'ozzxjr': { weight: 4, children: ['ojzpzsa', 'enmoyyj', 'nqzlzs'] },
    'sqwovza': { weight: 2 },
    'hqpkdyb': { weight: 6, children: ['bvviqc', 'jxcxv', 'ozugcs'] },
    'ybfqzep': { weight: 2 },
    'bpmrgr': { weight: 4 },
    'qcldyng': { weight: 2 },
    'sbsfo': { weight: 8 },
    'saxar': { weight: 8 },
    'xucrab': { weight: 3 },
    'mdktwy': { weight: 6 },
    'nkegq': { weight: 9 },
    'gawbtev': { weight: 0, children: ['jleqdi', 'dylrpo', 'zxdhxrb'] },
    'htgvzw': { weight: 0, children: ['rpanfr', 'zdaorg'] },
    'fojnd': { weight: 2 },
    'yaera': { weight: 3, children: ['mpwlly', 'gxzxapn'] },
    'vlaowv': { weight: 6, children: ['dxzahps', 'mtfqemm'] },
    'lwujegj': { weight: 1, children: ['emreip', 'ujnas'] },
    'rtwur': { weight: 1, children: ['shgcr', 'euoqdcd'] },
    'dniub': { weight: 9 },
    'qaqgap': { weight: 8 },
    'oucqw': { weight: 6, children: ['qrlmd', 'gwpzvb', 'aywrlw'] },
    'nesoknh': { weight: 2 },
    'rpzit': { weight: 9 },
    'uwoyjsd': { weight: 3 },
    'rawfw': { weight: 8 },
    'bnsqqv': { weight: 8 },
    'sgvaf': { weight: 3, children: ['ihmqbiu', 'mweox', 'zkaqnra', 'uiiqr', 'athdvrh', 'qqmpq', 'jfnknli'] },
    'ysmqsps': { weight: 1, children: ['hfjazyf', 'lyorl', 'mhassg', 'euypgtx'] },
    'facjth': { weight: 7, children: ['wvaynsl', 'ygykyu', 'bhaebe', 'qcsfpn'] },
    'gdvqsyp': { weight: 8, children: ['zdiygz', 'ksbjftc', 'uekiz'] },
    'bsnxzz': { weight: 5 },
    'qyqthsz': { weight: 5, children: ['nkegq', 'jrjkj'] },
    'xcjxzq': { weight: 6, children: ['hmjzw', 'ylmwjuo', 'xupkjdt'] },
    'nbykdlk': { weight: 9, children: ['gmtsea', 'qahfrp'] },
    'acgiwii': { weight: 3 },
    'xquzvw': { weight: 1 },
    'kdrke': { weight: 1 },
    'bpznnqh': { weight: 8 },
    'zhckae': { weight: 8 },
    'ypzqp': { weight: 9, children: ['jewrs', 'juytoy'] },
    'vrqdv': { weight: 9 },
    'klcuumi': { weight: 2, children: ['swqgxh', 'rtzodmx', 'xmendwz'] },
    'bsqpcne': { weight: 2, children: ['xulpd', 'ixwoprg', 'rqqxoou', 'xykvys', 'nfchpk'] },
    'oxerrb': { weight: 9 },
    'hivsxt': { weight: 7, children: ['bipyp', 'botmw'] },
    'kmyvyx': { weight: 0 },
    'nfkbhas': { weight: 5 },
    'hkcghm': { weight: 6 },
    'kqokslj': { weight: 0 },
    'djxvowe': { weight: 6 },
    'jypccpq': { weight: 6 },
    'yktmvtf': { weight: 7 },
    'dezgi': { weight: 0 },
    'bojjcl': { weight: 1 },
    'zsancei': { weight: 5 },
    'jnmgovh': { weight: 6 },
    'buyazh': { weight: 9, children: ['jrksg', 'zhckae'] },
    'sppxgv': { weight: 6, children: ['hgblqo', 'xpqnuh'] },
    'cguzndh': { weight: 5 },
    'shgcr': { weight: 2 },
    'hmrrarb': { weight: 3, children: ['wadeqe', 'floca'] },
    'lmueep': { weight: 3 },
    'ntugl': { weight: 4 },
    'ftatt': { weight: 2 },
    'pgnbhl': { weight: 0, children: ['qovcwth', 'bhxmn', 'ibagnjs'] },
    'qsods': { weight: 5 },
    'xngnhi': { weight: 1, children: ['jfclt', 'fpnjjy', 'wjkqpqr'] },
    'relztcy': { weight: 2 },
    'vtphqb': { weight: 7 },
    'qahfrp': { weight: 8 },
    'bqppw': { weight: 9 },
    'hxowycm': { weight: 6, children: ['okmwjoa', 'undaxyj'] },
    'oojlo': { weight: 1, children: ['losjvw', 'ekpvnh'] },
    'fgbsxh': { weight: 8 },
    'mmotdue': { weight: 3, children: ['relztcy', 'qwtheza'] },
    'tienxkv': { weight: 8, children: ['rqbjjuo', 'wdgfw'] },
    'qwfosq': { weight: 5, children: ['aunrdo', 'ntadc'] },
    'anoza': { weight: 7, children: ['bdzkzv', 'dzugjhb', 'hgltuwc', 'odmmo', 'tienxkv', 'yowbd'] },
    'kioxu': { weight: 9, children: ['qkdiej', 'kqfob'] },
    'ybjld': { weight: 4 },
    'juytoy': { weight: 0 },
    'xstgov': { weight: 6, children: ['wnjtvt', 'bnqutso'] },
    'tapirho': { weight: 3 },
    'vjhwn': { weight: 8, children: ['xrmslfs', 'djejdy', 'oopiw'] },
    'iroikgp': { weight: 5, children: ['vqbfan', 'gkegoh'] },
    'jtfdy': { weight: 9 },
    'ybqzq': { weight: 3, children: ['vpsls', 'bbsvfl', 'isoayc'] },
    'pqsfee': { weight: 2 },
    'bhxmn': { weight: 9 },
    'amhug': { weight: 3 },
    'yxzdn': { weight: 9 },
    'wvaynsl': { weight: 5 },
    'hrhfd': { weight: 7 },
    'yrbpdq': { weight: 7 },
    'ipppjn': { weight: 2 },
    'ygnlbv': { weight: 8 },
    'zjhnhz': { weight: 3, children: ['fsose', 'tbwieh', 'myhgys', 'nltqkvf'] },
    'facddx': { weight: 1, children: ['hwldx', 'ydgusm'] },
    'gnbmz': { weight: 9 },
    'bmxoqy': { weight: 7 },
    'pyhohkx': { weight: 7, children: ['nghcpr', 'wpgziu'] },
    'sqnfn': { weight: 5, children: ['ztxjb', 'noqmsh'] },
    'gzqutgv': { weight: 5, children: ['gqwfi', 'yenbb', 'reqlm', 'krquje'] },
    'tgqxadm': { weight: 1 },
    'qjdqn': { weight: 7, children: ['wzruwk', 'eegwdp'] },
    'mvldvib': { weight: 4 },
    'gbmexj': { weight: 9 },
    'ppedet': { weight: 4, children: ['qhfoy', 'lpgtx', 'xucrab', 'oioqg'] },
    'ctdcrl': { weight: 8, children: ['kufceqa', 'qebkt', 'ocuhfpd', 'isvfa'] },
    'bhaebe': { weight: 5 },
    'amooqlb': { weight: 3 },
    'tcaex': { weight: 5, children: ['cvxcr', 'mxikfk', 'xzfrad', 'tlwqwlk'] },
    'uoenrx': { weight: 9 },
    'ewvlay': { weight: 4 },
    'zkwzctg': { weight: 8 },
    'qkjed': { weight: 2 },
    'jewrs': { weight: 0 },
    'snquxtz': { weight: 3, children: ['dzrywb', 'hoilkqz'] },
    'miidkpe': { weight: 6 },
    'hgltuwc': { weight: 6, children: ['ptyuh', 'wfixt'] },
    'oybow': { weight: 8 },
    'dtsdw': { weight: 1 },
    'qfzyvjr': { weight: 6, children: ['ehclf', 'nmvki'] },
    'ymerus': { weight: 6 },
    'cbefqk': { weight: 5, children: ['fgzwvuy', 'yaawixo'] },
    'nyeur': { weight: 7 },
    'baimp': { weight: 9 }
};
let found = null;

_.forOwn(tower, (deets, level) => {
    if(!found && deets.children) {
        if(_(tower).filter(deets => deets.children).filter(deets => deets.children.indexOf(level) >= 0).value().length === 0) {
            found = level;
        }
    }
});

console.log(found);